---
title: "Accommodating Data Pathologies in Conjoint Studies"
output: github_document
---

## Abstract

Respondent behavior in conjoint studies often deviates from the assumptions of random utility theory. We refer to deviations from normative choice behavior as data pathologies. A variety of models have been developed that attempt to correct for specific pathologies (i.e., screening rules, respondent quality, attribute non-attendance, etc.). While useful, these approaches tend to be both conceptually complex and computational intensive. As such, these approaches have not widely diffused into the practice of marketing research. In this paper we draw on innovations in machine learning to develop a practical approach that relies on (clever) randomization strategies and ensembling to simultaneously accommodate multiple data pathologies in a single model. We provide tips and tricks on how to implement this approach in practice.

For general details on GitHub usage, project organization, and project workflow, see [Research Assistant Training](https://github.com/marcdotson/ra-training).

## Project Organization

- `Code`: includes utilities and model scripts written in python, R, and Stan
- `Data`: Simulated data sets used by conjoint models
- `Figures`: images and plots from demos, tutorials, and paper
- `Paper`: includes the paper submitted for publication
- `Presentation`: slides, demos, and tutorials
